name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: jakakolwiek
          MYSQL_USER: marek
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t marekk33/repo:latest .
        docker push marekk33/repo:latest

    - name: SSH into Virtual Machine and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_SSH_PORT }}
        script: |
          docker pull mysql:latest
          docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=jakakolwiek -e MYSQL_USER=marek -e MYSQL_PASSWORD=root -p 3306:3306 mysql:latest
          
          docker pull marekk33/repo:latest
          docker run -d --name your-container-name -p 8080:8080 marekk33/repo:latest
